### ISSUE TITLE
How many epochs during training?

### ISSUE THREAD

**Issue by Guliisgreat** [nijkah/MaskTrack_Box#1]
Hi. If I want to use train.py with pre-trained deeplab model according to your default configs, how many epochs needed to reach mIOU=65.4 ?

**Comment by nijkah** [comment]
Thank you for your interests on my repository.
Actually, the performance of the model varies from time to time.

Unlike image classification or semantic segmentation, many video object segmentation models (including MaskTrack) use previous predictions as input to the next frame.
It results in the fluctuation of the performance.

The best result in this repository are picked by dumped models.
Roughly, the best performance is reached in 15,000 ~ 20,000 iterations with batch 12.
Since the total number of images in [DAVIS2016, ECSSD, MSRA10k) is 13,079, it is approximately 13 ~ 18 epochs.
